name: Unit tests with DeepSpeed on Ascend NPU

on:
  workflow_dispatch:
    inputs:
      runner:
        required: true
        type: choice
        options:
          - linux-aarch64-a2-1
          - linux-aarch64-a2-2
          - linux-aarch64-a2-4
          - linux-aarch64-a2-8
        default: 'linux-aarch64-a2-1'
        description: 'Runner to run on'

  pull_request:
    paths:
      - '.github/workflows/deepspeed.yaml'
      - 'requirements/**'
  push:
    branches:
      - 'main'
      - 'deepspeed'
    paths:
      - '.github/workflows/deepspeed.yaml'
      - 'requirements/**'

  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write

# Bash shells do not use ~/.profile or ~/.bashrc so these shells need to be explicitly
# declared as "shell: bash -el {0}" on steps that need to be properly activated.
# It's used to activate ascend-toolkit environment variables.
defaults:
  run:
    shell: bash -el {0}

jobs:
  deepspeed-ut:
    name: Run unit tests with DeepSpeed
    runs-on: ${{ inputs.runner || 'linux-aarch64-a2-1' }}
    container:
      image: swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci/cann:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Config mirrors
        run: |
          sed -i 's|ports.ubuntu.com|mirrors.tuna.tsinghua.edu.cn|g' /etc/apt/sources.list
          pip config set global.index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
          pip config set global.retries 5

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y \
              git gcc g++ make cmake ninja-build python-is-python3 python3-pip

      - name: Check container state
        run: |
          npu-smi info
          echo "source /usr/local/Ascend/cann/set_env.sh" >> ~/.bashrc

      - name: Install pytorch
        run: |
          pip install torch torch_npu==2.7.1rc1 torchvision torchaudio \
              numpy==1.* cloudpickle tornado ml-dtypes PyYAML decorator -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple

      - name: List torch_npu version
        run: |
          python -c "import torch; print('torch:', torch.__version__)"
          python -c "import torch_npu; print('torch_npu:', torch_npu.__version__)"

      - name: Install transformers
        run: |
          git clone https://github.com/huggingface/transformers
          cd transformers
          pip install .

      - name: Checkout deepspeed
        uses: actions/checkout@v4
        with:
          repository: microsoft/DeepSpeed
          path: deepspeed

      - name: Install deepspeed
        working-directory: deepspeed
        run: |
          pip install -r ../requirements/requirements_deepspeed.txt
          pip install .[1bit,autotuning,inf]
          ds_report

      - name: Python environment
        run: |
          pip list

      - name: Run unit tests
        working-directory: deepspeed/tests/unit
        run: |
          unset TORCH_CUDA_ARCH_LIST # only jit compile for current arch

          pytest --verbose accelerator/*
          pytest --verbose autotuning/*
          pytest --verbose model_parallelism/*
          pytest --verbose monitor/*
          pytest --verbose utils/*
          pytest --verbose runtime/test_ds_config_model.py
          pytest --verbose runtime/pipe/test_pipe_schedule.py
          pytest --verbose runtime/zero/test_zero_config.py
          pytest --verbose runtime/zero/test_zero_tiled.py
          pytest --verbose runtime/zero/test_zeropp.py
          pytest --verbose runtime/test_autocast.py
          pytest --verbose runtime/test_data.py
          pytest --verbose runtime/zero/test_zero_dynamic_class.py
