name: Test llamacpp

on:
  workflow_dispatch:
    inputs:
      runner:
        required: true
        type: choice
        options:
          - linux-arm64-npu-1
          - linux-arm64-npu-2
          - linux-arm64-npu-4
          - linux-aarch64-310p-1
          - linux-aarch64-310p-2
        default: "linux-arm64-npu-1"
        description: "The runner selected to run on"
    
  pull_request:
    branches:
      - "llamacpp"
    paths:
      - ".github/workflows/llamacpp2.yml"
  push:
    branches:
      - "llamacpp"
    paths:
      - ".github/workflows/llamacpp2.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.set.outputs.runner }}
      images: ${{ steps.set.outputs.images }}
    steps:
      - name: Set outputs
        id: set
        run: |
          echo "runner=${{ inputs.runner  || 'linux-arm64-npu-1' }}" >> $GITHUB_OUTPUT
          if [[ ${{ runner }} == "linux-aarch64-310p-1" || \
                ${{ runner }} == "linux-aarch64-310p-2" ]]; then
            echo 'images=["ascendai/cann:8.2.rc1-310p-ubuntu22.04-py3.11","ascendai/cann:8.2.rc1-310p-openeuler22.03-py3.11"]' >> $GITHUB_OUTPUT
          else
            echo 'images=["ascendai/cann:8.2.rc1-910b-ubuntu22.04-py3.11","ascendai/cann:8.2.rc1-910b-openeuler22.03-py3.11","ascendai/cann:latest"]' >> $GITHUB_OUTPUT
          fi

  test:
    name: Build llama.cpp on OpenEuler for Arm64
    needs: prepare
    strategy:
      matrix:
        image : ${{ fromJSON(needs.prepare.outputs.images) }}
        device:
          - 'ascend910b3'
        build:
          - 'Release'
    runs-on: ${{ needs.prepare.outputs.runner }}
    container:
      image: ${{ matrix.image }}
      env:
        HF_ENDPOINT: https://hf-mirror.com

    steps:
      - name: Show NPU info
        run: |
          npu-smi info

      - name: Config mirrors
        run: |
          sed -i 's|ports.ubuntu.com|mirrors.tuna.tsinghua.edu.cn|g' /etc/apt/sources.list
          pip config set global.index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple

      - name: Install system dependencies
        run: |
          apt-get update -y && \
          apt-get install -y \
              git gcc g++ make cmake ninja-build curl \
              libcurl4-openssl-dev

      - name: Config git
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout llama.cpp
        uses: actions/checkout@v4
        with:
          repository: ggerganov/llama.cpp
          path: llama.cpp

      - name: Install torch
        run: |
          pip install torch torch_npu==2.7.1rc1

      - name: List torch version
        id: list-torch-version
        shell: bash
        run: |
          torch_version=$(python -c "from importlib.metadata import version;print(version('torch'))")
          echo "torch-version=${torch_version}" >> $GITHUB_OUTPUT

      - name: Build llama.cpp
        working-directory: llama.cpp
        run: |
          export LD_LIBRARY_PATH=${ASCEND_TOOLKIT_HOME}/lib64:${ASCEND_TOOLKIT_HOME}/$(uname -m)-linux/devlib/:${LD_LIBRARY_PATH}
  
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=${{ matrix.build }} \
            -DGGML_CANN=on \
            -DSOC_TYPE=${{ matrix.device }}
          cmake --build build -j $(nproc)
    
      - name: Define operator list
        id: define-ops
        run: |
            echo "ops=REPEAT, GET_ROWS, SET_ROWS, DUP, ADD, ADD1, SUB, ACC, MUL,
            DIV, ABS, NEG, GELU, GELU_ERF, SILU, GELU_QUICK, TANH, RELU, SIGMOID,
            HARDSIGMOID, HARDSWISH, EXP, ELU, SGN, STEP, REGLU, GEGLU, GEGLU_REF, SWIGLU,
            GEGLU_QUICK, NORM, GROUP_NORM, CONCAT, UPSCALE, PAD, ARANGE, TIMESTEP_EMBEDDING,
            LEAKY_RELU, RMS_NORM, MUL_MAT, MUL_MAT_ID, SCALE, SQR, SQRT, CLAMP,
            CPY, CONT, DIAG_MASK_INF, SOFT_MAX, ROPE, IM2COL, POOL_2D, SUM, SUM_ROWS,
            ARGSORT, ARGMAX, COS, SIN, CONV_TRANSPOSE_1D, LOG, MEAN, PAD_REFLECT_1D,
            COUNT_EQUAL, FLASH_ATTN_EXT" >> $GITHUB_OUTPUT

      - name: test backend ops
        working-directory: llama.cpp/build/bin
        run: |
          for op in $(echo ${{ steps.define-ops.outputs.ops }} | tr ',' '\n')
          do
            echo "Testing operator: $op"
            ./test-backend-ops test -o $op
          done
    
      - name: Download model
        run: |
          pip install huggingface_hub
          mkdir -p llama.cpp/models/Qwen2.5-0.5B-Instruct
          huggingface_cli download \
            --resume-download Qwen/Qwen2.5-0.5B-Instruct \
            --local-dir llama.cpp/models/Qwen2.5-0.5B-Instruct

      - name: Accuracy check
        working-directory: llama.cpp/build
        run: |
          ./bin/llama-perplexity \
            --model ../models/Qwen2.5-0.5B-Instruct \
            --prompt "What is the capital of France?" \
            -n 1 \
            --batch-size 1 \
            --log-file accuracy.json

      - name: Run llama-bench
        working-directory: llama.cpp/build
        run: |
          ./bin/llama-bench \
            --model ../models/Qwen2.5-0.5B-Instruct \
            -n 1 \
            --batch-size 1 \
            --threads $(nproc)

      - name: Run llama-batched-bench
        working-directory: llama.cpp/build
        run: |
          ./bin/llama-batched-bench \
            --model ../models/Qwen2.5-0.5B-Instruct \
            -c 2048 \
            -b 128 \
            -ub 512 \
            -npp 32,64 \
            -ntg 32,64 \
            -npl 1,2,4,8,16,32

      - name: Run llama-parallel
        working-directory: llama.cpp/build
        run: |
          ./bin/llama-parallel \
            --model ../models/Qwen2.5-0.5B-Instruct \
            -n 1 \
            --batch-size 1 \
            --threads $(nproc) \
            --log-file parallel.json
#