name: llama.cpp

# defaults:
#   run:
#     shell: bash -el {0}
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/llamacpp.yaml'
      - 'requirements/**'

  push:
    paths:
        - '.github/workflows/llamacpp.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cann: ['python3.10-cann8.0.rc3.beta1']
        build: ['Release']

    container:
      image: ascendai/cann:openeuler-${{ matrix.cann }}

    steps:
    - uses: actions/checkout@v4

    - name: Install llamacpp
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 30
        max_attempts: 3
        retry_on: error
        command: |
          yum update -y
          yum install git cmake gcc gcc-c++ make -y
          
          git clone https://github.com/ggerganov/llama.cpp.git

    - name: Build
      run: |
          # cat /root/.bashrc
          # source /usr/local/Ascend/ascend-toolkit/set_env.sh
          # cat /usr/local/Ascend/ascend-toolkit/set_env.sh
          # export LIBRARY_PATH=${ASCEND_TOOLKIT_HOME}/lib64:${LIBRARY_PATH}
          # echo "-----------111111111-----------------"
          # echo $LIBRARY_PATH
          # echo "----------111111111111------------------"
          cd llama.cpp
          mkdir build
          cd build
          
          export ASCEND_TOOLKIT_HOME=/usr/local/Ascend/ascend-toolkit/latest
          export LD_LIBRARY_PATH=${ASCEND_TOOLKIT_HOME}/lib64:${ASCEND_TOOLKIT_HOME}/lib64/plugin/opskernel:${ASCEND_TOOLKIT_HOME}/lib64/plugin/nnengine:${ASCEND_TOOLKIT_HOME}/opp/built-in/op_impl/ai_core/tbe/op_tiling/lib/linux/$(arch):$LD_LIBRARY_PATH
          export LD_LIBRARY_PATH=${ASCEND_TOOLKIT_HOME}/tools/aml/lib64:${ASCEND_TOOLKIT_HOME}/tools/aml/lib64/plugin:$LD_LIBRARY_PATH
          export PYTHONPATH=${ASCEND_TOOLKIT_HOME}/python/site-packages:${ASCEND_TOOLKIT_HOME}/opp/built-in/op_impl/ai_core/tbe:$PYTHONPATH
          export PATH=${ASCEND_TOOLKIT_HOME}/bin:${ASCEND_TOOLKIT_HOME}/compiler/ccec_compiler/bin:${ASCEND_TOOLKIT_HOME}/tools/ccec_compiler/bin:$PATH
          export ASCEND_AICPU_PATH=${ASCEND_TOOLKIT_HOME}
          export ASCEND_OPP_PATH=${ASCEND_TOOLKIT_HOME}/opp
          export TOOLCHAIN_HOME=${ASCEND_TOOLKIT_HOME}/toolkit
          export ASCEND_HOME_PATH=${ASCEND_TOOLKIT_HOME}

          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build }} -DGGML_CANN=on && make -j32
          
  ubuntu-unit-tests:
    runs-on: ubuntu-latest

    container:
      image: ascendai/cann

    steps:
    - uses: actions/checkout@v4

    - name: Install llamacpp
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 30
        max_attempts: 3
        retry_on: error
        command: |
          apt-get update -y
          apt-get install git cmake build-essential make -y
          
          git clone https://github.com/ggerganov/llama.cpp.git

    - name: Build
      run: |
          # cat /root/.bashrc
          # source /usr/local/Ascend/ascend-toolkit/set_env.sh
          # cat /usr/local/Ascend/ascend-toolkit/set_env.sh
          # export LIBRARY_PATH=${ASCEND_TOOLKIT_HOME}/lib64:${LIBRARY_PATH}
          # echo "-----------111111111-----------------"
          # echo $LIBRARY_PATH
          # echo "----------111111111111------------------"
          cd llama.cpp
          
          export ASCEND_TOOLKIT_HOME=/usr/local/Ascend/ascend-toolkit/latest
          export LD_LIBRARY_PATH=${ASCEND_TOOLKIT_HOME}/lib64:${ASCEND_TOOLKIT_HOME}/lib64/plugin/opskernel:${ASCEND_TOOLKIT_HOME}/lib64/plugin/nnengine:${ASCEND_TOOLKIT_HOME}/opp/built-in/op_impl/ai_core/tbe/op_tiling/lib/linux/$(arch):$LD_LIBRARY_PATH
          export LD_LIBRARY_PATH=${ASCEND_TOOLKIT_HOME}/tools/aml/lib64:${ASCEND_TOOLKIT_HOME}/tools/aml/lib64/plugin:$LD_LIBRARY_PATH
          export PYTHONPATH=${ASCEND_TOOLKIT_HOME}/python/site-packages:${ASCEND_TOOLKIT_HOME}/opp/built-in/op_impl/ai_core/tbe:$PYTHONPATH
          export PATH=${ASCEND_TOOLKIT_HOME}/bin:${ASCEND_TOOLKIT_HOME}/compiler/ccec_compiler/bin:${ASCEND_TOOLKIT_HOME}/tools/ccec_compiler/bin:$PATH
          export ASCEND_AICPU_PATH=${ASCEND_TOOLKIT_HOME}
          export ASCEND_OPP_PATH=${ASCEND_TOOLKIT_HOME}/opp
          export TOOLCHAIN_HOME=${ASCEND_TOOLKIT_HOME}/toolkit
          export ASCEND_HOME_PATH=${ASCEND_TOOLKIT_HOME}

          cmake -B build -DCMAKE_BUILD_TYPE=release -DGGML_CANN=on && cmake --build build -j $(nproc)



    

    
    
