name: llama.cpp

defaults:
  run:
    shell: bash -el {0}
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/llamacpp.yaml'
      - 'requirements/**'

  push:
    paths:
        - '.github/workflows/llamacpp.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cann: ['python3.10-cann8.0.rc3.beta1']
        build: ['Release']

    container:
      image: ascendai/cann:openeuler-${{ matrix.cann }}

    steps:
    - uses: actions/checkout@v4

    - name: Install llamacpp
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 30
        max_attempts: 3
        retry_on: error
        command: |
          yum update -y
          yum install git cmake gcc gcc-c++ make -y
          
          git clone https://github.com/ggerganov/llama.cpp.git

    - name: Build
      run: |
          # source /root/.bashrc
          # export LIBRARY_PATH=${ASCEND_TOOLKIT_HOME}/lib64:${LIBRARY_PATH}
          cd llama.cpp
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build }} -DGGML_CANN=on
          cmake --build . -j $(nproc)



    

    
    
