name: llama.cpp

defaults:
  run:
    shell: bash -el {0}
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/llamacpp.yaml'
      - 'requirements/**'

  push:
    paths:
        - '.github/workflows/llamacpp.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cann: ['python3.10-cann8.0.rc2.beta1']
        build: ['Release']

    container:
      image: ascendai/cann:openeuler-${{ matrix.cann }}

    steps:
    - uses: actions/checkout@v4

    - name: Install llamacpp
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 30
        max_attempts: 3
        retry_on: error
        command: |
          yum update -y
          yum install git cmake gcc gcc-c++ make -y  
          git clone https://github.com/ggerganov/llama.cpp.git

    - name: Build
      run: |
          cd llama.cpp
          mkdir build
          cd build
          export LD_LIBRARY_PATH=/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/aarch64-linux/devlib/x86_64/:${LD_LIBRARY_PATH}
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build }} -DGGML_CANN=on -DSOC_TYPE=ascend910b3 -DCMAKE_OSX_ARCHITECTURES=arm64 && cmake --build .
          
  ubuntu-unit-tests:

    runs-on: ubuntu-latest

    container:
      image: ascendai/cann

    steps:
    - uses: actions/checkout@v4
        
    - name: Install llamacpp
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 30
        max_attempts: 3
        retry_on: error
        command: |
          apt-get update -y
          apt-get install git cmake build-essential make -y   
          git clone https://github.com/ggerganov/llama.cpp.git

    - name: Build
      run: |
          cd llama.cpp
          export LD_LIBRARY_PATH=/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/aarch64-linux/devlib/:/usr/local/Ascend/ascend-toolkit/latest/aarch64-linux/devlib/x86_64/:${LD_LIBRARY_PATH}
          cmake -B build -DCMAKE_BUILD_TYPE=release -DGGML_CANN=on -DSOC_TYPE=ascend910b3 -DCMAKE_OSX_ARCHITECTURES=arm64 && cmake --build build -j $(nproc)

  ubuntu-arm64-test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
        
      - uses: uraimo/run-on-arch-action@v2
        name: Run Docker on ARM64
        with:
          arch: aarch64
          distro: ubuntu22.04
          install: |   
            # apt-get update
            # apt-get install -y docker.io
            # docker pull ascendai/cann:latest
            uname -a
          base_image: --platform=linux/arm64 ascendai/cann:openeuler-python3.10-cann8.0.rc2.beta1
          run: |
            uname -a
            yum update -y
            yum install git cmake gcc gcc-c++ make -y  
            git clone https://github.com/ggerganov/llama.cpp.git

            cd llama.cpp
            export LD_LIBRARY_PATH=/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/aarch64-linux/devlib/:${LD_LIBRARY_PATH}
            cmake -B build -DCMAKE_BUILD_TYPE=release -DGGML_CANN=on -DSOC_TYPE=ascend910b3 && cmake --build build

    

    
    
