name: llama.cpp

defaults:
  run:
    shell: bash -el {0}
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/llamacpp.yaml'
      - 'requirements/**'

  push:
    paths:
        - '.github/workflows/llamacpp.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write

jobs:
  unit-tests:
    runs-on: [self-hosted, ascend, npu]
    strategy:
      matrix:
        cann: ['python3.10-cann8.0.rc2.beta1']
        build: ['Release']
    container:
      image: ascendai/cann:openeuler-${{ matrix.cann }}
      ports:
        - 80
      volumes:
        - /usr/local/dcmi:/usr/local/dcmi
        - /usr/local/bin/npu-smi:/usr/local/bin/npu-smi 
        - /usr/local/Ascend/driver/lib64/:/usr/local/Ascend/driver/lib64/
        - /usr/local/Ascend/driver/version.info:/usr/local/Ascend/driver/version.info
        - /etc/ascend_install.info:/etc/ascend_install.info   
      options: --name llamacpp_cmake
               --device /dev/davinci4
               --device /dev/davinci_manager
               --device /dev/devmm_svm
               --device /dev/hisi_hdc

    steps:
    - uses: actions/checkout@v4

    - name: Install llamacpp
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 30
        max_attempts: 3
        retry_on: error
        command: |
          yum update -y
          yum install git cmake gcc gcc-c++ make -y  
          git clone https://github.com/ggerganov/llama.cpp.git

    - name: Build
      run: |
          cd llama.cpp
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build }} -DGGML_CANN=on -DSOC_TYPE=ascend910b3 && cmake --build .. --config release
          
  ubuntu-unit-tests:
    runs-on: [self-hosted, ascend, npu]
    strategy:
      matrix:
        cann: ['python3.10-cann8.0.rc2.beta1']
        build: ['Release']
    container:
      image: ascendai/cann
      ports:
        - 80
      volumes:
        - /usr/local/dcmi:/usr/local/dcmi
        - /usr/local/bin/npu-smi:/usr/local/bin/npu-smi 
        - /usr/local/Ascend/driver/lib64/:/usr/local/Ascend/driver/lib64/
        - /usr/local/Ascend/driver/version.info:/usr/local/Ascend/driver/version.info
        - /etc/ascend_install.info:/etc/ascend_install.info   
      options: --name llamacpp_cmake
               --device /dev/davinci0
               --device /dev/davinci_manager
               --device /dev/devmm_svm
               --device /dev/hisi_hdc

    steps:
    - uses: actions/checkout@v4

    - name: Install llamacpp
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 30
        max_attempts: 3
        retry_on: error
        command: |
          apt-get update -y
          apt-get install git cmake build-essential make -y   
          git clone https://github.com/ggerganov/llama.cpp.git

    - name: Build
      run: |
          cd llama.cpp
          cmake -B build -DCMAKE_BUILD_TYPE=release -DGGML_CANN=on -DSOC_TYPE=ascend910b3 && cmake --build build -j $(nproc)



    

    
    
