name: Build and publish onnxruntime image

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - onnx
    paths:
      - 'script/**'
      - '.github/workflows/ort-pypi.yaml'
  # schedule:
  #   - cron: '0 11 * * 0'

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      last_tag: ${{ steps.get_tag.outputs.last_tag }}
      latest_tag: ${{ steps.get_latest_tag.outputs.latest_tag }}
      skip_build: ${{ steps.compare_tags.outputs.skip_build }}

    steps:
      - id: get_tag
        run: |
          pypi_tag=$(python3 - <<'EOF'
          import urllib.request, json
          url = "https://pypi.org/pypi/onnxruntime-cann/json"
          with urllib.request.urlopen(url) as resp:
              data = json.load(resp)
          print("v" + data["info"]["version"])
          EOF
          )

          echo "last_tag=$pypi_tag" >> $GITHUB_OUTPUT

      - id: get_latest_tag
        run: |
          REPO="microsoft/onnxruntime"
          API="https://api.github.com/repos/$REPO/tags"

          LATEST_TAG=$(curl -s --connect-timeout 15 --max-time 30 "$API" | \
                      grep '"name":' | head -n 1 | cut -d '"' -f 4)
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      - id: compare_tags
        run: |
          GITHUB_TAG=${{ steps.get_latest_tag.outputs.latest_tag }}
          PYPI_TAG=${{ steps.get_tag.outputs.last_tag }}

          echo "GitHub latest: $GITHUB_TAG"
          echo "PyPI latest: $PYPI_TAG"

          if [ "$GITHUB_TAG" = "$PYPI_TAG" ]; then
            echo "No new tag detected. Skipping build."
            echo "skip_build=true" >> $GITHUB_OUTPUT
          else
            echo "New tag detected: $GITHUB_TAG"
            echo "skip_build=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: check
    # if: needs.check.outputs.skip_build == 'false'
    name: Build for ${{ matrix.build_name }}(${{ matrix.runner }})
    runs-on: ${{ matrix.runner }}
    container:
      image: ${{ matrix.image }}
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

    strategy:
      matrix:
        include:
          - arch: x86_64
            runner: linux-aarch64-a2-1
            image: swr.cn-south-1.myhuaweicloud.com/onnx-repo/manylinux_2_28_x86_64:latest
            build_name: x86_64-py312-cann8.5.0

          - arch: aarch
            runner: ubuntu-22.04
            image: swr.cn-south-1.myhuaweicloud.com/onnx-repo/manylinux_2_28_x86_64:latest
            build_name: aarch64-py312-cann8.5.0

          - arch: aarch
            runner: linux-aarch64-a2-1
            image: swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci/cann:latest
            build_name: aarch64-py312-cann9.0.0
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Configure PyPI credentials
        run: |
          cat > ~/.pypirc <<EOF
            [distutils]
            index-servers = onnxruntime-cann
            [onnxruntime-cann]
            repository = https://upload.pypi.org/legacy/
            username = __token__
            password = $PYPI_TOKEN
          EOF

      - name: Checkout ONNX Runtime
        uses: actions/checkout@v6
        with:
          repository: microsoft/onnxruntime
          path: onnxruntime
          fetch-depth: 1

      - name: Build ONNX Runtime wheel
        working-directory: onnxruntime
        shell: bash
        run: |
          # git checkout ${{ needs.check.outputs.latest_tag }}
          git checkout -b v1.24.1 refs/tags/v1.24.1
          source $ASCEND_TOOLKIT_HOME/set_env.sh
          ./build.sh --allow_running_as_root \
            --config Release \
            --build_shared_lib \
            --parallel \
            --use_cann \
            --build_wheel \
            --skip_tests

      - name: Upload to PyPI
        if: needs.check.outputs.skip_build == 'false'
        working-directory: onnxruntime
        run: |
          echo "开始上传到 PyPI (onnxruntime-cann)..."
          python3 -m twine upload --non-interactive --skip-existing --repository onnxruntime-cann build/Linux/Release/dist/*.whl
